### ISSUE TITLE
Inquire about the data info generation process

### ISSUE THREAD

**Issue by SuperBruceJia** [lidq92/WaDIQaM#10]
Dear Dingquan,

Thanks a lot for your great work! It really helps!

One thing I wanna inquire about is the data info generation process. Is any script available to generate such full info for a random dataset like CSIQ?

Thanks in advance and have a nice day!

Best,

Shuyue

**Comment by SuperBruceJia** [comment]
I followed your instructions and make the data info for CSIQ Database.
For details, check this file: https://github.com/SuperBruceJia/oneIQA/blob/main/data/datainfo_maker.m.

**Comment by SuperBruceJia** [comment]
BTW, Dingquan,

I'm still figuring out the principle of `index`? 

```matlab
% index: `random` train-val-test split index, 1000 runs
index = cell2mat(arrayfun(@(i)randperm(length(ref_names)), 1:1000, 'UniformOutput', false)'); 
```

Why use such a code to generate the `index`?

Best,

Shuyue

**Comment by SuperBruceJia** [comment]
Dear Dingquan,

As shown in the [LIVE Dataset Download Page](https://live.ece.utexas.edu/research/Quality/subjective.htm), the number of distorted images are 779. However, for this dataset, the number of iamges should be 982 since there are 233 images in the jpeg folder. 

Could you share your LIVE-make-info.m file in order to generate a new fullinfo.mat file?

Thanks in advance.

Best,

Shuyue

**Comment by anirban-ivan** [comment]
Hello @SuperBruceJia  I have the same question regarding LIVE dataset, can you enlighten me on this?
