### ISSUE TITLE
您好，我在您的网络基础上改动为NRIQA遇到了一些问题

### ISSUE THREAD

**Issue by OOOred** [lidq92/WaDIQaM#2]
您的FRIQA网络我已经成功训练并测试，之后我想要将这个网络修改为无参考的模型进行训练并测试，我做了如下的改动：将配置文件的模式修改为WaDIQAM-NR，将RandomCropPatches切片函数的参数修改为NR，然后运行训练脚本，切分数据集的过程中会产生如下问题：RuntimeError: expected a non-empty list of Tensors，我尝试着将RandomCropPatches函数的ref_crops删除，还有IQADataset中的有关ref_crops的部分都做了删除，并将model中的x_ref删除，只输出其他的值，之前的问题得以解决，但是会出现这个问题：
Traceback (most recent call last):
  File "D:/pythonworkplace/MY-WAdeepIQA/WaDIQaM.py", line 138, in <module>
    sq_std.append(data[3])
IndexError: list index out of range
面对这个问题我多次尝试但是没有能够成功解决，如果将[3]删除虽然能解决掉字面的bug但是在运行一段时间后还会提示只有一个tensor元素可以被转化为python scalar的错误。究其原因还是我对于代码中定义的sq_std的意义不明确，不知道在无参考模型中如何处理这个变量，希望能够得到您的指点，帮助我完成无参考的训练，万分感激！！

**Comment by lidq92** [comment]
@OOOred 我后来更新了代码，后面的代码应该更清晰有条理了。

`sq_std`是人们对同一张图像的主观打分的偏差（标准差），数据集中有随图像数据一起提供。

要做代码修改最好还是先把代码读懂，最起码每个模块的输入输出和作用要懂呢。
