### ISSUE TITLE
Could you please provide a pretrained model for No-reference IQA?

### ISSUE THREAD

**Issue by bomb2peng** [lidq92/WaDIQaM#6]
Hello, thanks for sharing your good work. I only found full-reference model in checkpoint dir. Could you please provide a pretrained model for No-reference IQA?

**Comment by lidq92** [comment]
I have not tuned the NR model, and currently, the results are far below the reported results.
So I would not provide the pre-trained model unless similar results are reproduced.
You can refer to the test code of the original authors, see [dmaniry/deepIQA](https://github.com/dmaniry/deepIQA).
